DSEG	SEGMENT
	teststruct	DW	10 DUP(0)
	bb	DW	10 DUP(0)
	char	DW	2 DUP(0)
	inta	DW	10 DUP(0)
	float	DW	2 DUP(0)
	TEMP	DW	9 DUP(0)
	CONST	DW	1,100,2,10,3,4,9,0,6,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
DSEG	ENDS
CSEG	SEGMENT
	ASSUME	CS:CSEG,DS:DSEG
FUNC	PROC	NEAR
	MOV	AX,char[12]
	MOV	BX,CONST[4]
	ADD	AX,BX
	MOV	char[12],AX
	MOV	AX,char[12]
	CALL	COUT
	RET
FUNCTT	PROC	NEAR
	CALL	FUNC
	RET
MAX	PROC	NEAR
	MOV	AX,char[20]
	MOV	char[22],AX
	MOV	AX,char[22]
	CALL	COUT
	RET
COUT	PROC	NEAR
	MOV	SI,10
	MOV	CX,0
next1:	MOV	DX,0
	DIV	SI
	PUSH	DX
	INC	CX
	CMP	AX,0
	JNZ	next1
next2:	POP	DX
	ADD	DL,30H
	MOV	AH,02H
	INT	21H
	LOOP	next2
	RET
COUT	ENDP
start:	MOV	AX,DSEG
	MOV	DS,AX
	MOV	AX,CONST[2]
	MOV	char[0],AX
	MOV	AX,CONST[8]
	MOV	char[18],AX
	MOV	AX,CONST[10]
	MOV	char[20],AX
	CALL	MAX
	MOV	AX,char[24]
	MOV	char[22],AX
	CALL	FUNCTT
	MOV	AX,CONST[12]
	MOV	char[0],AX
t0:	MOV	AX,char[0]
	MOV	BX,CONST[14]
	CMP	AX,BX
	MOV	TEMP[2],AX
	MOV	AX,TEMP[2]
	AND	AX,AX
	JZ	t1
	MOV	AX,bb[0]
	MOV	TEMP[4],AX
	MOV	AX,TEMP[4]
	MOV	bb[0],AX
	MOV	AX,char[0]
	DEC	AX
	MOV	char[0],AX
	JMP	t0
t1:	MOV	AX,CONST[14]
	MOV	char[0],AX
t2:	MOV	AX,char[0]
	MOV	BX,CONST[6]
	CMP	AX,BX
	MOV	TEMP[8],AX
	MOV	AX,TEMP[8]
	AND	AX,AX
	JZ	t3
	MOV	AX,bb[0]
	MOV	TEMP[10],AX
	MOV	AX,TEMP[10]
	CALL	COUT
	MOV	AX,char[0]
	INC	AX
	MOV	char[0],AX
	JMP	t2
t3:	MOV	AX,char[6]
	MOV	BX,char[0]
	ADD	AX,BX
	MOV	char[6],AX
	MOV	AX,char[6]
	MOV	BX,CONST[16]
	MUL	BX
	MOV	char[6],AX
	MOV	AX,char[6]
	CALL	COUT
CSEG	ENDS
	END	START
